### ISSUE TITLE
Versioning Content

### ISSUE THREAD

**Issue by wilfriedroset** [kostiantyn-nemchenko/ansible-role-patroni#84]
One of the best practice recommended in [ansible galaxy documentation](https://galaxy.ansible.com/docs/contributing/version.html) is to use versioning content. Doing so allow users to pin the version of the role in order to avoid surprise in production during the next `ansible-galaxy install`.
This require only to add tags to commit which is not done at the moment in this repository.

Here is an example of my side project `requirements.yml`
```yaml
---
roles:
  - name: brianshumate.consul
    version: v2.5.4
  - name: kostiantyn-nemchenko.patroni

collections: []
```

As you can see I can pin the version I want yo use for **brianshumate.consul** but not for **kostiantyn-nemchenko.patroni** due to missing tags.

What do you think about adding 1.0.0 tag to the latest commit?
